[package]
name = "hermes-rust-example"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
hippius-hermes-core = { path = "../../crates/core" }
tokio = { version = "1.35", features = ["full", "rt-multi-thread"] }
anyhow = "1.0"
shellexpand = "3.1"
serde_json = "1.0"
